### ISSUE TITLE
Question: Does js for the browser count as a different language?

### ISSUE THREAD

**Issue by thecolorblocks** [EvanZhouDev/TheDonutProject#1]
I have one donut to contribute. But for the browser. ASCII pre tag. Not sure if it counts as a different language though.

**Comment by EvanZhouDev** [comment]
Go with `donut.html`, and just use a script tag or something... that would be awesome. Thank you for contributing!

**Comment by Rudxain** [comment]
This gives me an idea. [Wasm has an official "source code" format](https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format), so it should be possible to do `donut.wat`!

**Comment by thecolorblocks** [comment]
> This gives me an idea. [Wasm has an official "source code" format](https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format), so it should be possible to do `donut.wat`!

Very much looking forward to it!

**Comment by Rudxain** [comment]
@thecolorblocks #23
