### ISSUE TITLE
Any ideas for how I can make assembly code donut shaped?

### ISSUE THREAD

**Issue by IOKG04** [EvanZhouDev/TheDonutProject#19]
I translated donut.c into assembly (nasm syntax to be specific) over the last day, but only now noticed nasm doesnt support putting multiple instructions on one line (and that is also the case with most assemblers, or at least all I could find)  
I wondered if anyone here knew of an assembler that could do that.

If not my two main ideas are either to fork nasm and try to build in that functionality myself, though it'd mean that anyone who wants to verify my code also needs to have my specific version of nasm, or to make it be a c file (though with a different extension) and use inline asm there.

If anyone here got a better idea, please tell me, thanks :)

**Comment by IOKG04** [comment]
Oh, if anyone is interested in my code, it can be found [here](https://github.com/IOKG04/TheDonutProject/tree/donut.asm-(x86)/donuts/donut.asm).  
The [build.sh](https://github.com/IOKG04/TheDonutProject/tree/donut.asm-(x86)/donuts/build.sh) script is just there so i dont have to type 3 commands every time I want to re-compile the program.

**Comment by IOKG04** [comment]
I just had another idea: Since gas supports multiple instructions per line, one way to make `donut.s` happen would be to get a version of `donut.c` in gas syntax assembly, which is really easy to get by just telling gcc to output the assembly, and to then have it be assembled by gas/gcc when one wants to use it.

I think I'll just do that since it is probably the easiest option, though I'll keep the branch with my code in case someone here knows how we could make that work.

**Comment by EvanZhouDev** [comment]
This looks awesome! I wanted to do this but as someone who spends most of their time developing NPM packages and working with React/Next.js, I just couldn't figure out how asm works 😅

Would love to collab together with some of you guys to make yt videos, as I'm aware you have a channel too!

**Comment by EvanZhouDev** [comment]
Hey @IOKG04, it has just been brought to my attention that `donut.c` doesn't compile anymore 😅

Do you want to try and reinvent the wheel (donut) to some degree? I know that you can do a bit of C...

**Comment by IOKG04** [comment]
@EvanZhouDev I could also imagine that whoever found that bug might have forgotten to link the two libraries the program depends on (with `-lm -lc` that should be possible on `gcc`)

If the problem isn't just that, I could try to re-write it.

**Comment by EvanZhouDev** [comment]
Yeah, I think it is just broken, it says that ISO C99 and later don't support implicit int and function declarations... I am not really familiar with C

**Comment by IOKG04** [comment]
I only have a (12 year old, barely functioning) laptop rn, but I can look into it once Im back at my PC (so Sunday or Monday).

Also regarding the second part of ur first comment (which I only saw now, sry), Id be interested in a collab :D
