### ISSUE TITLE
Link to lib-less `float`-less implementation

### ISSUE THREAD

**Issue by Rudxain** [EvanZhouDev/TheDonutProject#20]
The `README` would be more helpful if it included this link: https://www.a1k0n.net/2021/01/13/optimizing-donut.html

Please add it somewhere. This will make it easier for beginners to implement it in langs with minimal (or none) std-libs, and langs that only support integers. It has the nice side-effect of being more efficient (on most langs)

**Comment by EvanZhouDev** [comment]
Added in 809f751 👍

**Comment by Rudxain** [comment]
Thank you!
