### ISSUE TITLE
"See also" section

### ISSUE THREAD

**Issue by Rudxain** [EvanZhouDev/TheDonutProject#21]
I think the `README` should include links to related projects, such as:

- [smallest valid programs](https://github.com/mathiasbynens/small)
- [HW](https://github.com/leachim6/hello-world)
- [Rosetta Stone of Code](https://rosettacode.org)

Although simply adding the `rosetta` tag (to the GH repo "topics", not `README`) should be enough. It also increases SEO

**Comment by EvanZhouDev** [comment]
Done in 8712f27 👍
