### ISSUE TITLE
Alternative implementations?

### ISSUE THREAD

**Issue by Rudxain** [EvanZhouDev/TheDonutProject#25]
What if there are multiple valid implementations in the same lang?

Examples:
- JS can use `console.log` & `console.clear` in a browser environment to emulate donut.c
- JS can assume `stdout` is connected to a Unix-like terminal (as is the case in most Node-like envs). This allows JS to perfectly replicate donut.c
- PyGame and Turtle are libraries that allow Python scripts to render graphics on-screen, using wildly-different APIs.
- JS can use `textarea` to emulate a terminal within a browser window (no `console` required)
- [RR](https://github.com/Rick-Lang/rickroll-lang) can either call Py libs (such as `math`), or be "pure" by using fixed-point arithmetic (#20)

I ask this because the file-name rules are so strict that alt-impls would collide

**Comment by EvanZhouDev** [comment]
Yes, any ideas to fix the file-name rules? 😅

**Comment by Rudxain** [comment]
The easiest solution I can think of (right now) is to allow 1 "barely free-form" prefix or suffix. I think suffixes would be better, as they're adjacent to the extension, which better conveys its similarity to extensions. Example: `donut.turtle.py` vs `turtle.donut.py`.

The hard part is choosing a nice delimiter, lol. For the sake of simplicity, let's constrain ourselves to printable-ASCII. Now, it could be anything from this charset: `"_- |."`, or even combinations/sequences of them!

**Comment by Rudxain** [comment]
Wait, I forgot about the key collisions in `info.json` 😅. Any schema change would be a breaking-change, but it's forgivable considering the schema is implicit

**Comment by Rudxain** [comment]
I was thinking more, and thought of 2 possibilities:
- Rename all keys to include the suffix, like `py` => `turtle.py`
- Reuse existing keys, but have inner suffix-keys each pointing to the same object-type as usual (`{name: string, github: string}`)

**Comment by IOKG04** [comment]
I feel like the easiest way would be to use a `.` as a delimiter and to say that everything after the first `.` counts as the file extension (so basically your first option), so that for any key `[xyz]` the file would be `donut.[xyz]`. Wouldn't conflict with the existing rules and would still allow for more flexibility.

**Comment by Rudxain** [comment]
> I feel like the easiest way would be to use a `.` as a delimiter

I agree. Seems like a reasonable/sensible choice. Especially because JSON is usually accessed using dot-notation.

> and to say that everything after the first `.` counts as the file extension

That's a bit overkill. But, on second thought, that's exactly how `*.tar.gz` is to be interpreted! So there's already "prior art" of that

**Comment by EvanZhouDev** [comment]
@IOKG04 @Rudxain I added something for alternate implementations in the README, but it's a bit lengthy/confusing 😅

If y'all want to make it easier to understand, feel free!

**Comment by Rudxain** [comment]
@EvanZhouDev Referring to fixed-point as "pure" may be confusing for 2 reasons:
- May be confused with pure functional programming.
- Is not the same as `no_std` and/or "lib-less".

When I said "pure" when talking about RR, it was because Python libs are foreign (bindings) to the lang and are implementation-specific (the C implementation doesn't export them)
