### ISSUE TITLE
Small issue in `donutGenerator.py`

### ISSUE THREAD

**Issue by IOKG04** [EvanZhouDev/TheDonutProject#26]
To keep the actual amount of characters `donutGenerator.py` gives when given a single argument, either the `.84` in line 34 has to be changed into a `.8775` or the `.35` in the following line needs to become a `.4` (like in the original).

Please note when choosing one of those options, that a lower value in line 35 (aka a higher value in line 34) leads to a donut with relatively speaking less center.

It's less of an issue that needs fixing right now, but the math nerd on me just wanted to point that out. (I can give mathematical proof of why the values should be like I described if requested)

**Comment by EvanZhouDev** [comment]
Ah, yes, I wanted to make the inside of the donut slightly smaller. I should've gone through the math, but I was too lazy to reverse engineer it 😅

Thank you for pointing it out! (I'm to some degree [a math nerd too](https://github.com/EvanZhouDev/cubie) lol)
