### ISSUE TITLE
Smaller output size

### ISSUE THREAD

**Issue by IOKG04** [EvanZhouDev/TheDonutProject#44]
I am currently working on an [asciidots](https://esolangs.org/wiki/AsciiDots) implementation of `donut.c`, but (at least as far as I can see) the performance of the asciidots interpreter scales with file size.  
I currently have a demo with 1760 cells that can hold one value each (comparable to `z` in `donut.c`), and it already only runs with a couple ticks per second (each frame will probably take around a couple thousand to ten thousand ticks to render, so I think you can see the problem).

Besides further optimizing my code of course, one of my ideas to get it running a little smoother would be to scale down the output resolution by 2 (thus only needing 440 storage cells, greatly improving performance). Would that be okay or is that too far from the original `donut.c`?

**Comment by EvanZhouDev** [comment]
That’s completely fine! This would be a beautiful donut to have…

By the way, feel free to set the rules! You have more contributions in this repo than I, and I’ll accept whatever you feel like doing, as long as it’s remotely in the bounds of the original rules :)
